Repository doksuri5/frontend, pull requests merged in 2024-06, with the labels that each got.

#6 Button 공통 컴포넌트 생성
  next.config.mjs
  package-lock.json
  package.json
  src/app/page.tsx
  src/app/svg/eyeShow_icon.svg
  src/app/svg/fab_icon.svg
  src/app/svg/fnb.svg
  src/app/svg/language_en.svg
  src/app/svg/refresh_icon.svg
  src/components/common/Button.tsx
Labels: ⚙️ 개발환경, 🎨 디자인, 🛠️ 기능개발

#3 Input 공통 컴포넌트 생성
  package-lock.json
  package.json
  src/app/page.tsx
  src/assets/icons/eye-hide-icon.tsx
  src/assets/icons/eye-show-icon.tsx
  src/components/common/Caption.tsx
  src/components/common/Input.tsx
  src/components/common/Label.tsx
Labels: ⚙️ 개발환경, 🎨 디자인, 🛠️ 기능개발

#8 Card 공통 컴포넌트 생성
  next.config.mjs
  src/app/svg/card2Rectangle.svg
  src/app/svg/card3Rectangle_large.svg
  src/app/svg/card3Rectangle_small.svg
  src/components/common/Card.tsx
Labels: ⚙️ 개발환경, 🎨 디자인, 🛠️ 기능개발

#7 Dropdown 공통 컴포넌트 생성
  package-lock.json
  package.json
  src/app/(design)/system/page.tsx
  src/app/globals.css
  src/components/common/Dropdown.tsx
Labels: ⚙️ 개발환경, 🎨 디자인, 🛠️ 기능개발

#14 Card 컴포넌트 리뷰 반영 수정
  next.config.mjs
  src/components/common/Card.tsx
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🛠️ 기능개발

#15 [QJ5-23] 공통 컴포넌트 CheckBox/Toggle
  public/icons/checkbox_default.svg
  public/icons/checkbox_select.svg
  src/app/(design)/system/page.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Toggle.tsx
  src/components/common/index.ts
Labels: 🛠️ 기능개발

#16 [QJ5-28] 헤더 컴포넌트 마크업 및 디자인
  src/app/layout.tsx
  src/components/layout/Header.tsx
Labels: 🎨 디자인

#17 [QJ5-39] 페이지 레이아웃 디자인 적용
  src/app/layout.tsx
  src/app/page.tsx
Labels: 🎨 디자인

#20 [QJ5-43] Next에서 SVG 파일 설정
  next.config.mjs
  src/components/layout/Header.tsx
  svgr.d.ts
  tsconfig.json
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🕹️ 트러블슈팅

#25 [QJ5-46] 인풋 컴포넌트 이슈 수정
  src/components/common/Caption.tsx
  src/components/common/Input.tsx
  src/components/common/Label.tsx
Labels: 🐞 버그, 🎨 디자인

#22 [QJ5-32] Modal 공통 컴포넌트 작성
  src/app/globals.css
  src/components/common/Modal.tsx
  src/components/common/index.ts
  tailwind.config.ts
Labels: ⚙️ 개발환경, 🎨 디자인, 🛠️ 기능개발

#18 [QJ5-25] 메인페이지 구현
  package-lock.json
  package.json
  public/icons/AI_icon.svg
  public/icons/warning_icon.svg
  src/app/(home)/layout.tsx
  src/app/(home)/news.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/List/StockItem.tsx
  src/hooks/use-draggable.tsx
  tailwind.config.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#27 [QJ5-48] 헤더 컴포넌트 상단 고정 및 body 스타일 수정
  src/app/layout.tsx
  src/components/layout/Header.tsx
Labels: 🎨 디자인

#23 [QJ5-37] 발견 페이지 마크업 및 디자인
  public/icons/time_icon.svg
  src/app/(discovery)/_components/DiscoveryInput.tsx
  src/app/(discovery)/_components/DiscoveryNews.tsx
  src/app/(discovery)/_components/DiscoverySection.tsx
  src/app/(discovery)/_components/DiscoveryStocks.tsx
  src/app/(discovery)/_components/PopularSearches.tsx
  src/app/(discovery)/_components/RecentSearches.tsx
  src/app/(discovery)/_components/index.ts
  src/app/(discovery)/layout.tsx
  src/app/(discovery)/page.tsx
  src/app/globals.css
  src/components/common/List/NewsList.tsx
  src/types/SearchDataType.ts
  src/types/index.ts
Labels: ♻️ 리팩토링, 🎨 디자인

#29 [QJ5-45] 발견 페이지 스켈레톤 적용 및 폴더 구조 변경
  src/app/(discovery)/_components/DiscoveryNews.tsx
  src/app/(discovery)/_components/DiscoveryStocks.tsx
  src/app/(discovery)/_components/PopularSearches.tsx
  src/app/(discovery)/_components/RecentSearches.tsx
  src/app/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/(discovery)/discovery/_components/DiscoveryNews.tsx
  src/app/(discovery)/discovery/_components/DiscoverySection.tsx
  src/app/(discovery)/discovery/_components/DiscoveryStocks.tsx
  src/app/(discovery)/discovery/_components/PopularSearches.tsx
  src/app/(discovery)/discovery/_components/RecentSearches.tsx
  src/app/(discovery)/discovery/_components/_skeleton/PopularSearchItemSkeleton.tsx
  src/app/(discovery)/discovery/_components/_skeleton/RecentSearchItemSkeleton.tsx
  src/app/(discovery)/discovery/_components/index.ts
  src/app/(discovery)/discovery/layout.tsx
  src/app/(discovery)/discovery/page.tsx
  src/components/common/List/skeleton/FindNewsSkeleton.tsx
  src/components/common/List/skeleton/StockItemSkeleton.tsx
  src/components/common/Skeleton.tsx
  src/components/common/index.ts
Labels: 🐞 버그, ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#30 fix: 헤더 컴포넌트 z-index 수정
  src/components/layout/Header.tsx
Labels: 🐞 버그

#31 [QJ5-32] Modal 공통 컴포넌트 백드롭 close 옵션 추가
  src/app/(mypage)/mypage/language-setting/page.tsx
  src/app/(mypage)/mypage/layout.tsx
  src/app/(mypage)/mypage/page.tsx
  src/app/(mypage)/mypage/terms/page.tsx
  src/components/common/Modal.tsx
Labels: 🛠️ 기능개발

#33 design: 루트 레이아웃 최대 너비 1200px 고정
  src/app/layout.tsx
  src/components/layout/Header.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#35 [QJ5-59] Alert 컴포넌트 생성
  src/app/(discovery)/discovery/_components/DiscoverySection.tsx
  src/components/common/Alert.tsx
  src/components/common/Button.tsx
  src/components/common/Modal.tsx
  src/components/common/index.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발
