Repository doksuri5/frontend, pull requests merged in 2024-07, with the labels that each got.

#42 [QJ5-62] 로그인/회원가입 유효성
  package-lock.json
  package.json
  src/app/(auth)/_components/AgreeForm.tsx
  src/app/(auth)/_components/CommonLoginBtn.tsx
  src/app/(auth)/_components/FindIdComplete.tsx
  src/app/(auth)/_components/FindIdForm.tsx
  src/app/(auth)/_components/FindPasswordForm.tsx
  src/app/(auth)/_components/LoginForm.tsx
  src/app/(auth)/_components/RegisterForm.tsx
  src/app/(auth)/agree/page.tsx
  src/app/(auth)/find-id/page.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register-complete/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(auth)/verify-user/page.tsx
  src/app/globals.css
  src/hooks/useZodSchemaForm.tsx
  src/routes/path.ts
  src/types/AuthType.ts
Labels: ⚙️ 개발환경, 🎨 디자인

#37 [QJ5-64] 뉴스 디테일 페이지 UI 구현
  public/icons/AI_Summary.svg
  public/icons/translate_icon.svg
  src/app/(news)/news/[newsId]/_components/NewsDetail.tsx
  src/app/(news)/news/[newsId]/_components/RelatedNews.tsx
  src/app/(news)/news/[newsId]/_components/RelatedStocks.tsx
  src/app/(news)/news/[newsId]/_components/index.tsx
  src/app/(news)/news/[newsId]/page.tsx
  src/components/common/DescriptionWithLineBreaks.tsx
  src/components/common/List/FindNews.tsx
Labels: 🎨 디자인, 🛠️ 기능개발

#39 [QJ5-49] 챗봇 구현
  .env.example
  package-lock.json
  package.json
  public/icons/close_icon.svg
  public/icons/light_logo_base_icon.svg
  src/app/(home)/layout.tsx
  src/app/api/chat/route.ts
  src/app/api/chat/token/route.ts
  src/app/layout.tsx
  src/components/common/ChatBot.tsx
  src/components/common/ChatBox.tsx
  src/components/common/index.ts
  src/hooks/use-chat.ts
  src/hooks/use-disclosure.ts
  src/middleware.ts
  src/utils/generate-id.ts
Labels: ⚙️ 개발환경, 🎨 디자인, 🛠️ 기능개발

#41 [QJ5-66] 메인 페이지 리포트 컴포넌트 & 뉴스 컴포넌트 더미 추가
  package-lock.json
  package.json
  src/app/(home)/_components/SimpleReportCard.tsx
  src/app/(home)/news.tsx
  src/app/(home)/page.tsx
  src/components/common/SimpleRadarChart.tsx
Labels: 🎨 디자인

#40 [QJ5-51] 관심 주식 페이지 마크업 및 디자인
  public/icons/graph.png
  src/app/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/(discovery)/discovery/_components/DiscoveryStocks.tsx
  src/app/(discovery)/discovery/_components/PopularSearches.tsx
  src/app/(discovery)/discovery/_components/RecentSearches.tsx
  src/app/(mystock)/mystock/_components/MyStockBody.tsx
  src/app/(mystock)/mystock/_components/MyStockHeader.tsx
  src/app/(mystock)/mystock/_components/MyStockItem.tsx
  src/app/(mystock)/mystock/_components/MyStockModalSection.tsx
  src/app/(mystock)/mystock/_components/MyStockPopularSearches.tsx
  src/app/(mystock)/mystock/_components/MyStockRecentSearches.tsx
  src/app/(mystock)/mystock/_components/MyStockSearchResult.tsx
  src/app/(mystock)/mystock/_components/SearchItem.tsx
  src/app/(mystock)/mystock/_components/index.ts
  src/app/(mystock)/mystock/layout.tsx
  src/app/(mystock)/mystock/page.tsx
  src/app/(mystock)/mystock/stores/index.ts
  src/app/(mystock)/mystock/stores/useInterestStockStore.ts
  src/components/common/Alert.tsx
  src/components/common/List/StockItem.tsx
  src/stores/index.ts
  src/stores/useModalStore.ts
  src/stores/useRecentSearchStore.ts
  src/types/PopularDataType.ts
  src/types/SearchDataType.ts
  src/types/StockDataType.ts
  src/types/index.ts
  src/utils/stockPriceUtils.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#38 [QJ5-35] 뉴스 페이지 UI 구현
  package-lock.json
  package.json
  src/app/(news)/news/_components/NewsInfinityList.tsx
  src/app/(news)/news/_components/index.tsx
  src/app/(news)/news/page.tsx
  src/app/api/news/route.ts
  src/app/layout.tsx
  src/components/common/Card.tsx
  src/providers/QueryProvider.tsx
Labels: 🎨 디자인, 🛠️ 기능개발

#44 [QJ5-63] 메인페이지(로그인전) UI 구현
  public/images/intro_bg.png
  public/images/intro_content.png
  src/app/globals.css
  src/app/layout.tsx
  src/components/layout/Header.tsx
Labels: 🎨 디자인

#46 [QJ5-34] not found & error & loading 페이지 구현
  src/app/(home)/error.tsx
  src/app/(home)/page.tsx
  src/app/global-error.tsx
  src/app/loading.tsx
  src/app/not-found.tsx
  src/components/common/Spinner.tsx
  tailwind.config.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#45 [QJ5-71] 발견 페이지 input 리팩토링 및 관심 주식 페이지 스타일 수정
  src/app/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/(discovery)/discovery/page.tsx
  src/app/(mystock)/mystock/_components/MyStockBody.tsx
  src/app/(mystock)/mystock/_components/MyStockHeader.tsx
Labels: ♻️ 리팩토링, 🎨 디자인

#48 [QJ5-65] 리포트 페이지 UI 구현
  src/app/(news)/news/_components/index.tsx
  src/app/(report)/report/[stockReutersCode]/page.tsx
  src/app/(report)/report/_components/AIAnalystReport.tsx
  src/app/(report)/report/_components/ReportHeader.tsx
  src/app/(report)/report/_components/StockAIReport.tsx
  src/app/(report)/report/_components/StockChart.tsx
  src/app/(report)/report/_components/StockChartSection.tsx
  src/app/(report)/report/_components/StockDetail.tsx
  src/app/(report)/report/_components/index.tsx
  src/components/common/Card.tsx
  src/components/common/PoPularNews.tsx
  src/components/common/index.ts
  src/routes/path.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#47 [QJ5-68] 마이페이지 개인정보 수정 폼 유효성 검증 및 버그 수정
  public/icons/profile_icon.svg
  src/app/(mypage)/mypage/_components/EditPrivacyForm.tsx
  src/app/(mypage)/mypage/_components/EditProfileForm.tsx
  src/app/(mypage)/mypage/_components/PWCheckModal.tsx
  src/app/(mypage)/mypage/_components/PrivacyEditModal.tsx
  src/app/(mypage)/mypage/_components/ProfileEditModal.tsx
  src/app/(mypage)/mypage/_components/WithdrawModal.tsx
  src/app/(mypage)/mypage/_components/index.ts
  src/app/(mypage)/mypage/page.tsx
  src/app/(mypage)/mypage/terms/page.tsx
  src/components/common/User/UserPrivacyForm.tsx
  src/components/common/User/UserProfileForm.tsx
Labels: 🐞 버그, 🎨 디자인, 🛠️ 기능개발

#53 [QJ5-76] 메인페이지 디자인 수정
  src/app/[lang]/(home)/news.tsx
  src/app/[lang]/(home)/page.tsx
  src/components/common/List/NewsItem.tsx
Labels: 🎨 디자인

#54 [QJ5-69]로그인/회원가입 기능 구현 전 리팩토링
  src/app/[lang]/(auth)/_components/AgreeForm.tsx
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
  src/app/[lang]/(auth)/_components/RegisterForm.tsx
  src/app/[lang]/(auth)/_components/SocialLogin.tsx
  src/app/[lang]/(auth)/account/layout.tsx
  src/app/[lang]/(auth)/account/page.tsx
  src/app/[lang]/(auth)/account/profile-setup/layout.tsx
  src/app/[lang]/(auth)/account/profile-setup/page.tsx
  src/app/[lang]/(auth)/account/register/layout.tsx
  src/app/[lang]/(auth)/account/register/page.tsx
  src/app/[lang]/(auth)/account/verify-user/layout.tsx
  src/app/[lang]/(auth)/account/verify-user/page.tsx
  src/app/[lang]/(auth)/login/page.tsx
  src/app/[lang]/(auth)/profile-setup/page.tsx
  src/app/[lang]/(design)/system/page.tsx
  src/providers/RegisterProvider.tsx
  src/routes/path.ts
  src/stores/useRegisterStore.ts
  src/types/AuthType.ts
Labels: ♻️ 리팩토링, 🎨 디자인

#57 [QJ5-85] Auth.js 네이버 oauth 오류 수정
  .gitignore
  package-lock.json
  package.json
  patches/oauth4webapi+2.11.1.patch
Labels: 🐞 버그, ⚙️ 개발환경, 🛠️ 기능개발

#59 [QJ5-77] 뉴스와 주식 타입지정, Link태그 추가, Card컴포넌트 이미지 수정
  package-lock.json
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryStocks.tsx
  src/app/[lang]/(home)/news.tsx
  src/app/[lang]/(home)/page.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockItem.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockRecentSearches.tsx
  src/app/[lang]/(mystock)/mystock/page.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/NewsDetail.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedNews.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedStocks.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/index.tsx
  src/app/[lang]/(news)/news/_components/NewsInfinityList.tsx
  src/app/[lang]/(news)/news/_components/index.tsx
  src/app/[lang]/(report)/report/_components/AIAnalystReport.tsx
  src/app/[lang]/(report)/report/_components/ReportHeader.tsx
  src/app/[lang]/(report)/report/_components/StockAIReport.tsx
  src/app/[lang]/(report)/report/_components/StockDetail.tsx
  src/app/[lang]/(report)/report/_components/index.tsx
  src/app/api/news/route.ts
  src/components/common/Card.tsx
  src/components/common/List/FindNews.tsx
  src/components/common/List/NewsItem.tsx
  src/components/common/List/NewsList.tsx
  src/components/common/List/StockItem.tsx
  src/components/common/PoPularNews.tsx
  src/types/NewsDataType.ts
  src/types/StockDataType.ts
  src/types/index.ts
Labels: 🐞 버그, ♻️ 리팩토링

#60 [QJ5-93] 마이페이지 이용약관 API 호출 및 데이터 적용
  src/app/[lang]/(mypage)/mypage/_components/PolicyContent.tsx
  src/app/[lang]/(mypage)/mypage/_components/PolicyMain.tsx
  src/app/[lang]/(mypage)/mypage/terms/page.tsx
  src/utils/textUtils.tsx
Labels: 🛠️ 기능개발

#64 [QJ5-97] 로그인/회원가입, 이메일/비밀번호 찾기 기능 구현
  next-auth.d.ts
  package-lock.json
  src/app/[lang]/(auth)/_components/CommonLoginBtn.tsx
  src/app/[lang]/(auth)/_components/FindEmailComplete.tsx
  src/app/[lang]/(auth)/_components/FindEmailForm.tsx
  src/app/[lang]/(auth)/_components/FindIdComplete.tsx
  src/app/[lang]/(auth)/_components/FindIdForm.tsx
  src/app/[lang]/(auth)/_components/FindPasswordForm.tsx
  src/app/[lang]/(auth)/_components/Loading.tsx
  src/app/[lang]/(auth)/_components/LoginForm.tsx
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
  src/app/[lang]/(auth)/_components/RegisterForm.tsx
  src/app/[lang]/(auth)/_components/SocialLogin.tsx
  src/app/[lang]/(auth)/_components/Timer.tsx
  src/app/[lang]/(auth)/account/profile-setup/page.tsx
  src/app/[lang]/(auth)/account/register/page.tsx
  src/app/[lang]/(auth)/exist/layout.tsx
  src/app/[lang]/(auth)/exist/page.tsx
  src/app/[lang]/(auth)/find-email/layout.tsx
  src/app/[lang]/(auth)/find-email/page.tsx
  src/app/[lang]/layout.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/find-email/route.ts
  src/app/api/auth/nickname/route.ts
  src/auth.ts
  src/components/layout/Header.tsx
  src/lib/auth-action.ts
  src/lib/db.ts
  src/lib/schema.ts
  src/middleware.ts
  src/providers/AuthSession.tsx
  src/routes/path.ts
  src/types/AuthType.ts
  src/utils/reduce-image-size.ts
  tsconfig.json
Labels: 🛠️ 기능개발

#65 [QJ5-92] 주식 데이터에서 중립이 있을 경우 처리 추가, 주식 데이터 포맷팅 관련 함수 리팩터링
  src/app/[lang]/(home)/home/_components/SimpleReportCard.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockItem.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockPopularSearches.tsx
  src/app/[lang]/(mystock)/mystock/_components/SearchItem.tsx
  src/app/[lang]/(report)/report/_components/AIAnalystReport.tsx
  src/app/[lang]/(report)/report/_components/StockAIReport.tsx
  src/app/[lang]/(report)/report/_components/StockDetail.tsx
  src/app/[lang]/(report)/report/_components/index.tsx
  src/components/common/List/StockItem.tsx
  src/utils/stockPriceUtils.ts
  tailwind.config.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#66 [QJ5-99] 뉴스,리포트 페이지 스켈레톤 추가
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedNews.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedStocks.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/index.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/skeleton/NewsDetailSkeleton.tsx
  src/app/[lang]/(news)/news/_components/NewsInfinityList.tsx
  src/app/[lang]/(news)/news/_components/index.tsx
  src/app/[lang]/(report)/report/_components/index.tsx
  src/app/[lang]/(report)/report/_components/skeleton/AIAnalystReportSkeleton.tsx
  src/app/[lang]/(report)/report/_components/skeleton/ReportHeaderSkeleton.tsx
  src/app/[lang]/(report)/report/_components/skeleton/StockAIReportSkeleton.tsx
  src/app/[lang]/(report)/report/_components/skeleton/StockChartSectionSkeleton.tsx
  src/app/[lang]/(report)/report/_components/skeleton/StockDetailSkeleton.tsx
  src/components/common/CardSkeleton.tsx
  src/components/common/List/skeleton/NewsItemSkeleton.tsx
  src/components/common/PopularNewsSkeleton.tsx
Labels: 🛠️ 기능개발

#69 [QJ5-100] : 로그인 시 쿠키 발급 및 자동 로그인 기능 구현
  src/app/[lang]/(auth)/_components/LoginForm.tsx
  src/app/[lang]/(home)/page.tsx
  src/app/[lang]/layout.tsx
  src/auth.ts
  src/components/layout/Header.tsx
  src/lib/auth-action.ts
  src/lib/schema.ts
  src/middleware.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#70 [QJ5-78] 유저 프로필 수정 기능 구현
  next.config.mjs
  src/app/[lang]/(mypage)/mypage/_components/EditProfileForm.tsx
  src/app/[lang]/(mypage)/mypage/_components/MyPageMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/PolicyContent.tsx
  src/app/[lang]/(mypage)/mypage/_components/ProfileEditModal.tsx
  src/app/[lang]/(mypage)/mypage/_constants/stock.ts
  src/app/[lang]/(mypage)/mypage/_utils/profileUtils.ts
  src/app/[lang]/(mypage)/mypage/page.tsx
  src/stores/useUserStore.ts
  src/utils/reduce-image-size.ts
Labels: 🐞 버그, 🎨 디자인, 🛠️ 기능개발

#72 [QJ5-103] 로그인/회원가입 추가 작업
  next-auth.d.ts
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
  src/app/api/auth/find-email/route.ts
  src/auth.ts
Labels: ♻️ 리팩토링

#78 [QJ5-116] 회원가입-프로필 설정 페이지에 투자 성향 모달 추가
  src/app/[lang]/(auth)/_components/CommonAgreeLayout.tsx
  src/app/[lang]/(auth)/_components/CreditInfoAgree.tsx
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
  src/components/common/InvestPropensity.tsx
  src/data/InvestPropensityQuestions.ts
  src/hooks/useZodSchemaForm.tsx
  src/types/AuthType.ts
Labels: 🎨 디자인, 🛠️ 기능개발

#76 [QJ5-109] 리포트 페이지 ai 분석
  .env.example
  package-lock.json
  package.json
  src/actions/stock-analysis.ts
  src/actions/stock.ts
  src/app/[lang]/(home)/home/_components/ai-reports.tsx
  src/app/[lang]/(home)/home/page.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockItem.tsx
  src/app/[lang]/(news)/news/_components/index.tsx
  src/app/[lang]/(report)/report/[stockReutersCode]/page.tsx
  src/app/[lang]/(report)/report/_components/AIAnalystReport.tsx
  src/app/[lang]/(report)/report/_components/ReportHeader.tsx
  src/app/[lang]/(report)/report/_components/StockAIReport.tsx
  src/app/[lang]/(report)/report/_components/StockDetail.tsx
  src/app/[lang]/(report)/report/_components/index.tsx
  src/app/api/chat/route.ts
  src/app/api/report/stock-analysis/[code]/route.ts
  src/app/api/stocks/[code]/route.ts
  src/components/common/List/NewsItem.tsx
  src/components/common/SimpleRadarChart.tsx
  src/components/common/SimpleReportCard.tsx
  src/components/common/index.ts
  src/constants/stockCodes.ts
  src/hooks/use-get-action.ts
  src/lib/api.ts
  src/lib/db.ts
  src/types/ApiType.ts
  src/types/StockDataType.ts
  src/utils/stockPriceUtils.ts
  tailwind.config.ts
Labels: 🛠️ 기능개발

#79 [QJ5-112] 회원가입시 페이지 이탈 대응 및 자체 QA
  public/icons/warning_icon.svg
  src/app/[lang]/(auth)/_components/AgreeForm.tsx
  src/app/[lang]/(auth)/_components/CommonLayout.tsx
  src/app/[lang]/(auth)/_components/LoginForm.tsx
  src/app/[lang]/(auth)/login/error/layout.tsx
  src/app/[lang]/(auth)/login/error/page.tsx
  src/app/[lang]/(home)/layout.tsx
  src/app/[lang]/(home)/page.tsx
  src/app/[lang]/layout.tsx
  src/app/[lang]/not-found.tsx
  src/app/globals.css
  src/auth.ts
  src/components/layout/Header.tsx
  src/middleware.ts
  src/providers/AuthSession.tsx
  src/routes/path.ts
  src/utils/filter-mainpath.ts
Labels: ♻️ 리팩토링

#80 [QJ5-117] formData에 isAgreeCreditInfo, investPropensity 필드 추가
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
Labels: 🐞 버그

#83 [QJ5-113] 회원가입 이용약관 API 호출 및 데이터 적용
  src/actions/auth-action.ts
  src/actions/auth.ts
  src/app/[lang]/(auth)/_components/AgreeContent.tsx
  src/app/[lang]/(auth)/_components/AgreeForm.tsx
  src/app/[lang]/(auth)/_components/CommonAgreeLayout.tsx
  src/app/[lang]/(auth)/_components/LoginForm.tsx
  src/app/[lang]/(auth)/_components/Privacy.tsx
  src/app/[lang]/(auth)/_components/SocialLogin.tsx
  src/app/[lang]/(auth)/_components/Terms.tsx
  src/app/[lang]/(auth)/_components/index.ts
  src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
  src/components/layout/Header.tsx
  src/types/AuthType.ts
Labels: ♻️ 리팩토링

#84 [QJ5-106] 실제 유저 데이터 수정/탈퇴 기능 구현
  src/app/[lang]/(auth)/withdraw/page.tsx
  src/app/[lang]/(mypage)/mypage/_api/privacyApi.ts
  src/app/[lang]/(mypage)/mypage/_api/profileApi.ts
  src/app/[lang]/(mypage)/mypage/_api/withdrawApi.ts
  src/app/[lang]/(mypage)/mypage/_components/EditPrivacyForm.tsx
  src/app/[lang]/(mypage)/mypage/_components/EditProfileForm.tsx
  src/app/[lang]/(mypage)/mypage/_components/PolicyMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/VerifyModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/index.ts
  src/app/[lang]/(mypage)/mypage/_constants/stock.ts
  src/app/[lang]/(mypage)/mypage/page.tsx
  src/app/[lang]/(mypage)/mypage/terms/page.tsx
  src/components/common/Alert.tsx
  src/hooks/use-alert.ts
Labels: ♻️ 리팩토링, 🎨 디자인, 🛠️ 기능개발

#87 [QJ5-109] 주식 차트 기능 활성화
  src/actions/stock.ts
  src/app/[lang]/(report)/report/_components/StockChart.tsx
  src/app/[lang]/(report)/report/_components/StockChartSection.tsx
  src/app/[lang]/(report)/report/_components/index.tsx
  src/app/api/stocks/[...code]/route.ts
  src/app/api/stocks/[code]/route.ts
  src/types/StockDataType.ts
  src/utils/calculate-period.ts
Labels: 🛠️ 기능개발

#88 [QJ5-118] 빌드 이슈 수정 - 타입 에러 등
  src/app/[lang]/(auth)/_components/CommonAgreeLayout.tsx
  src/app/[lang]/(auth)/withdraw/page.tsx
  src/app/[lang]/(mypage)/mypage/_components/VerifyModal.tsx
  src/app/[lang]/(report)/report/_components/StockDetail.tsx
  src/hooks/use-get-action.ts
Labels: 🐞 버그

#85 [QJ5-38] 발견 페이지 API 적용
  next.config.mjs
  src/actions/news.ts
  src/actions/search.ts
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryNews.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryStocks.tsx
  src/app/[lang]/(discovery)/discovery/_components/PopularSearches.tsx
  src/app/[lang]/(discovery)/discovery/_components/RecentSearches.tsx
  src/app/[lang]/(discovery)/discovery/_components/SearchItem.tsx
  src/app/[lang]/(discovery)/discovery/_components/index.ts
  src/app/[lang]/(discovery)/discovery/page.tsx
  src/components/common/List/FindNews.tsx
  src/lib/api.ts
  src/lib/schema.ts
  src/middleware.ts
  src/types/NewsDataType2.ts
  src/types/SearchDataType.ts
  src/utils/getTimeDifference.ts
Labels: ♻️ 리팩토링, 🙋🏻 질문, 🛠️ 기능개발

#91 [QJ5-122] 회원탈퇴 후 메인페이지 이동 시 버그 수정, 메일 인증 초시계 위치 수정
  src/app/[lang]/(auth)/withdraw/page.tsx
  src/app/[lang]/(mypage)/mypage/_api/withdrawApi.ts
  src/app/[lang]/(mypage)/mypage/_components/VerifyModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
  src/middleware.ts
Labels: 🐞 버그, 🎨 디자인

#90 [QJ5-115] 뉴스페이지, 뉴스상세페이지 API 연동
  src/actions/news.ts
  src/app/[lang]/(news)/news/[newsId]/_components/NewsDetail.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedNews.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedStocks.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/index.tsx
  src/app/[lang]/(news)/news/[newsId]/page.tsx
  src/app/[lang]/(news)/news/_components/NewsInfinityList.tsx
  src/app/[lang]/(news)/news/_components/index.tsx
  src/app/[lang]/(news)/news/page.tsx
  src/components/common/List/NewsItem.tsx
  src/hooks/useInfiniteNews.ts
  src/utils/getDateWithoutTime.ts
  src/utils/truncateBackstring.ts
Labels: 🛠️ 기능개발

#99 [QJ5-123] 발견페이지 검색 엔터키 검색 이슈
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/[lang]/(report)/report/_components/index.tsx
Labels: ♻️ 리팩토링

#100 [QJ5-79] 다국어 설정 및 다국어 지원 설정
  next.config.mjs
  package-lock.json
  package.json
  src/app/[lang]/(mypage)/mypage/_api/languageApi.ts
  src/app/[lang]/(mypage)/mypage/_components/LanguageSettingMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/index.ts
  src/app/[lang]/(mypage)/mypage/language-setting/page.tsx
  src/app/[lang]/(mypage)/mypage/layout.tsx
  src/app/[lang]/(news)/news/page.tsx
  src/app/[lang]/[...not-found]/page.tsx
  src/app/[lang]/layout.tsx
  src/auth.ts
  src/components/common/PoPularNews.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
  src/get-dictionary.ts
  src/i18n.ts
  src/lib/i18n-config.ts
  src/middleware.ts
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🛠️ 기능개발

#101 [QJ5-127] 로그인/회원가입 버그
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
  src/app/[lang]/(auth)/_components/RegisterForm.tsx
  src/types/AuthType.ts
Labels: ♻️ 리팩토링

#102 [QJ5-131] 뉴스 페이지에서 발생하는 버그 수정
  src/actions/news.ts
  src/app/[lang]/(news)/news/_components/index.tsx
  src/components/common/Card.tsx
  src/components/common/List/NewsItem.tsx
  src/components/common/PoPularNews.tsx
Labels: 🐞 버그

#106 [QJ5-138] AI 뉴스 요약 기능 추가
  .env.example
  src/actions/stock-analysis.ts
  src/app/[lang]/(home)/home/news.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/NewsDetail.tsx
  src/app/api/ai/summary/route.ts
  src/app/api/chat/route.ts
  src/app/api/report/stock-analysis/[code]/route.ts
  src/components/common/ChatBox.tsx
  src/constants/ai-info.ts
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
  src/types/AuthType.ts
  src/types/NewsDataType.ts
Labels: 🛠️ 기능개발

#103 [QJ5-132] 프로필 설정 페이지에서 가입하기 버튼 클릭시 발생하는 버그 수정
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
Labels: 🐞 버그, ♻️ 리팩토링

#108 [QJ5-139] 몽구스를 사용한 조회 -> fetch 백엔드 통신
  src/auth.ts
Labels: 🐞 버그, ♻️ 리팩토링

#109 [QJ5-128] 발견 페이지 검색 박스 추가 및 초성 영어 검색 기능
  package-lock.json
  package.json
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryNews.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryStocks.tsx
  src/app/[lang]/(mystock)/mystock/stores/useInterestStockStore.ts
  src/components/common/Modal.tsx
  src/components/common/SearchBox.tsx
  src/components/common/index.ts
  src/hooks/use-debounced-search.tsx
  src/utils/filter-stock.ts
Labels: ♻️ 리팩토링, ⚙️ 개발환경, 🛠️ 기능개발

#111 [QJ5-140] 마이페이지 레이아웃 서버컴포넌트로 변경, 뉴스 페이지 타이틀 다국어 작업
  src/app/[lang]/(mypage)/mypage/_components/Navigation.tsx
  src/app/[lang]/(mypage)/mypage/layout.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedNews.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedStocks.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/skeleton/NewsDetailSkeleton.tsx
  src/app/[lang]/(news)/news/_components/index.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#113 [QJ5-142] 일반회원 auth의 session 오류
  src/actions/auth.ts
  src/auth.ts
  src/types/AuthType.ts
Labels: 🐞 버그

#112 [QJ5-143] 언어설정 오류 수정
  src/app/[lang]/(mypage)/mypage/_components/LanguageSettingMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
Labels: 🐞 버그

#115 [QJ5-145] 뉴스 디테일 페이지 - 줄바꿈 두번하도록 수정
  src/components/common/DescriptionWithLineBreaks.tsx
Labels: 🎨 디자인

#116 [QJ5-146] auth session name 추가
  src/auth.ts
Labels: 🐞 버그

#121 [QJ5-149] 발견, 관심주식 페이지 검색 버그 수정
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/[lang]/(discovery)/discovery/_components/SearchItem.tsx
  src/app/[lang]/(home)/home/news.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockRecentSearches.tsx
  src/components/common/Modal.tsx
  src/components/common/SearchBox.tsx
Labels: 🐞 버그, ♻️ 리팩토링

#122 [QJ5-150] 관심 주식 페이지 검색 박스 적용 및 기타 UI 수정
  src/app/[lang]/(mystock)/mystock/_components/MyStockModalSection.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockPopularSearches.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockSearchResult.tsx
  src/app/[lang]/(mystock)/mystock/_components/_skeleton/SearchItemSkeleton.tsx
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#124 [QJ5-157] 서버 컴포넌트 다국어 설정 버그 수정
  package-lock.json
  package.json
  src/app/[lang]/(mypage)/mypage/_components/EditPrivacyForm.tsx
  src/app/[lang]/(mypage)/mypage/_components/EditProfileForm.tsx
  src/app/[lang]/(mypage)/mypage/_components/LanguageSettingMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/MyPageMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/Navigation.tsx
  src/app/[lang]/(mypage)/mypage/_components/PolicyContent.tsx
  src/app/[lang]/(mypage)/mypage/_components/PrivacyEditModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/ProfileEditModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/VerifyModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
  src/app/[lang]/(mypage)/mypage/layout.tsx
  src/app/[lang]/layout.tsx
  src/components/layout/Header.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
  src/get-dictionary.ts
  src/i18n.ts
  src/middleware.ts
  src/utils/check-login.ts
Labels: 🐞 버그

#127 [QJ5-133] 로그인/회원가입 리팩토링
  next-auth.d.ts
  public/icons/close_icon.svg
  src/actions/auth.ts
  src/app/[lang]/(auth)/_components/AgreeForm.tsx
  src/app/[lang]/(auth)/_components/CommonLoadingBtn.tsx
  src/app/[lang]/(auth)/_components/CommonLoginBtn.tsx
  src/app/[lang]/(auth)/_components/FindEmailComplete.tsx
  src/app/[lang]/(auth)/_components/FindEmailForm.tsx
  src/app/[lang]/(auth)/_components/FindPasswordForm.tsx
  src/app/[lang]/(auth)/_components/LoginForm.tsx
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
  src/app/[lang]/(auth)/_components/RegisterForm.tsx
  src/app/[lang]/(auth)/_components/SocialLogin.tsx
  src/app/[lang]/(auth)/_components/index.ts
  src/app/[lang]/(auth)/account/verify-user/layout.tsx
  src/app/[lang]/(auth)/account/verify-user/page.tsx
  src/app/[lang]/(auth)/exist/page.tsx
  src/app/globals.css
  src/auth.ts
  src/components/common/ButtonSpinner.tsx
  src/components/common/CheckBox.tsx
  src/components/common/index.ts
  src/types/AuthType.ts
  tailwind.config.ts
  tsconfig.json
Labels: ♻️ 리팩토링

#126 [QJ5-152] 발견 페이지 리팩토링 및 다국어 적용
  src/actions/stock.ts
  src/app/[lang]/(discovery)/discovery/[search]/_components/DiscoveryNews.tsx
  src/app/[lang]/(discovery)/discovery/[search]/_components/DiscoveryStocks.tsx
  src/app/[lang]/(discovery)/discovery/[search]/_components/index.ts
  src/app/[lang]/(discovery)/discovery/[search]/_hooks/useShowMoreItems.ts
  src/app/[lang]/(discovery)/discovery/[search]/layout.tsx
  src/app/[lang]/(discovery)/discovery/[search]/page.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryInput.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryNews.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoverySection.tsx
  src/app/[lang]/(discovery)/discovery/_components/DiscoveryStocks.tsx
  src/app/[lang]/(discovery)/discovery/_components/PopularSearches.tsx
  src/app/[lang]/(discovery)/discovery/_components/RecentSearches.tsx
  src/app/[lang]/(discovery)/discovery/_components/SearchItem.tsx
  src/app/[lang]/(discovery)/discovery/_components/index.ts
  src/app/[lang]/(discovery)/discovery/layout.tsx
  src/app/[lang]/(discovery)/discovery/page.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedNews.tsx
  src/components/common/List/FindNews.tsx
  src/components/common/List/NewsItem.tsx
  src/components/common/List/StockItem.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
  src/types/NewsDataType2.ts
  src/utils/getTimeDifference.ts
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#128 [QJ5-158] 특정 페이지 이동불가 미들웨어 오류 수정
  src/app/[lang]/(mypage)/mypage/_components/LanguageSettingMain.tsx
  src/app/[lang]/layout.tsx
  src/middleware.ts
  src/utils/cookies.ts
Labels: 🐞 버그

#123 [Refactoring] 서버컴포넌트 변경 작업
  src/app/[lang]/(home)/home/_components/ai-reports.tsx
  src/app/[lang]/(home)/home/_components/interest-stocks.tsx
  src/app/[lang]/(home)/home/_components/news-box.tsx
  src/app/[lang]/(home)/home/_components/popular-interest-news.tsx
  src/app/[lang]/(home)/home/_components/recent-lookup.tsx
  src/app/[lang]/(home)/home/_components/recent-news.tsx
  src/app/[lang]/(home)/home/news.tsx
  src/app/[lang]/(home)/home/page.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockBody.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockFooter.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockItem.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx
  src/app/[lang]/(report)/report/[stockReutersCode]/page.tsx
  src/app/[lang]/(report)/report/_components/ReportHeader.tsx
  src/app/[lang]/(report)/report/_components/index.tsx
  src/components/common/ChatBox.tsx
  src/components/common/CountUp.tsx
  src/components/common/DraggableList.tsx
  src/components/common/List/StockItem.tsx
  src/components/common/PoPularNews.tsx
  src/components/common/ReportCardContent.tsx
  src/components/common/ReportCardHeader.tsx
  src/components/common/SimpleReportCard.tsx
  src/components/common/StockPrice.tsx
Labels: ♻️ 리팩토링

#125 [QJ5-141] 마이페이지-정보 수정에 투자성향진단 추가
  src/actions/investPropensity-action.ts
  src/app/[lang]/(mypage)/mypage/_api/investPropensityApi.ts
  src/app/[lang]/(mypage)/mypage/_components/InvestPropensityModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/MyPageMain.tsx
  src/app/[lang]/(mypage)/mypage/page.tsx
  src/components/common/InvestPropensity.tsx
  src/stores/useUserStore.ts
  src/types/investPropensityType.ts
Labels: 🛠️ 기능개발

#133 [QJ5-162] 잘못된 병합된 import 삭제
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
Labels: 🐞 버그

#132 [QJ5-161] 미들웨어 locale path regex 수정
  src/app/[lang]/(report)/report/[stockReutersCode]/layout.tsx
  src/app/[lang]/layout.tsx
  src/middleware.ts
Labels: 🐞 버그, ♻️ 리팩토링, 👥 공동작업

#134 [QJ5-164] 뉴스 페이지 이슈 수정
  src/app/[lang]/(auth)/_components/CommonLayout.tsx
  src/app/[lang]/(auth)/withdraw/page.tsx
  src/app/[lang]/(home)/home/_components/recent-news.tsx
  src/app/[lang]/(news)/news/_components/index.tsx
Labels: 🐞 버그

#129 [QJ5-159] 리포트 페이지 다국어 작업
  .env.example
  package-lock.json
  package.json
  src/actions/stock-analysis.ts
  src/actions/stock.ts
  src/app/[lang]/(home)/home/_components/popular-interest-news.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx
  src/app/[lang]/(report)/report/_components/AIAnalystReport.tsx
  src/app/[lang]/(report)/report/_components/StockChartSection.tsx
  src/app/[lang]/(report)/report/_components/StockDetail.tsx
  src/app/[lang]/(report)/report/_components/StockDetailHeader.tsx
  src/app/api/ai/stock-analysis/[code]/route.ts
  src/app/api/ai/summary/route.ts
  src/app/api/report/stock-analysis/[code]/route.ts
  src/app/api/stock/price/[reutersCode]/route.ts
  src/app/api/stock/price/currency-exchange/route.ts
  src/app/api/stock/price/sse/[reutersCode]/route.ts
  src/components/common/List/StockItem.tsx
  src/components/common/StockPrice.tsx
  src/components/common/Toggle.tsx
  src/constants/currency.ts
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
  src/hooks/use-chat.ts
  src/hooks/use-stock-price.ts
  src/lib/db.ts
  src/models/stock-analysis-schema.ts
  src/types/StockDataType.ts
  src/utils/check-login.ts
  vercel.json
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#135 [QJ5-165] 최신 뉴스 파라미터 빈값 전달 이슈
  src/app/[lang]/(home)/home/_components/recent-news.tsx
Labels: 🐞 버그

#136 [QJ5-163] 관심 주식 페이지 다국어 적용 및 버그 수정
  src/app/[lang]/(mystock)/mystock/_components/MyStockBody.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockFooter.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockHeader.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockHeaderButton.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockModalSection.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockPopularSearches.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockRecentSearches.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockSearchResult.tsx
  src/app/[lang]/(mystock)/mystock/_components/SearchItem.tsx
  src/app/[lang]/(mystock)/mystock/_components/index.ts
  src/components/common/SearchBox.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
  src/stores/useRecentSearchStore.ts
Labels: 🐞 버그, ♻️ 리팩토링, 🛠️ 기능개발

#137 [QJ5-166] 미들웨어 path regex 수정 - 비로그인시 홈 진입 안되는 이슈
  src/middleware.ts
Labels: 🐞 버그

#138 [QJ5-167] 미들웨어 일부 수정
  src/middleware.ts
Labels: 🐞 버그

#139 [QJ5-147] 마이페이지 다국어 작업
  src/app/[lang]/(auth)/_components/CreditInfoAgree.tsx
  src/app/[lang]/(auth)/_components/InvestPropensityQuestions.tsx
  src/app/[lang]/(auth)/withdraw/page.tsx
  src/app/[lang]/(mypage)/mypage/_components/EditPrivacyForm.tsx
  src/app/[lang]/(mypage)/mypage/_components/EditProfileForm.tsx
  src/app/[lang]/(mypage)/mypage/_components/LanguageSettingMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/MyPageMain.tsx
  src/app/[lang]/(mypage)/mypage/_components/VerifyModal.tsx
  src/app/[lang]/(mypage)/mypage/_components/WithdrawModal.tsx
  src/app/globals.css
  src/components/common/InvestPropensity.tsx
  src/data/InvestPropensityQuestions.ts
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🛠️ 기능개발

#140 [QJ5-144] 뉴스 다국어 작업
  src/actions/news.ts
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedNews.tsx
  src/app/[lang]/(news)/news/_components/NewsInfinityList.tsx
  src/components/common/List/NewsItem.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
  src/hooks/useInfiniteNews.ts
Labels: 🛠️ 기능개발

#143 [QJ5-171] 각종 이슈 해결 및 메인페이지 국제화 + 챗봇 개선
  src/app/[lang]/(auth)/account/layout.tsx
  src/app/[lang]/(discovery)/discovery/[search]/page.tsx
  src/app/[lang]/(discovery)/discovery/layout.tsx
  src/app/[lang]/(discovery)/discovery/page.tsx
  src/app/[lang]/(home)/home/_components/ai-reports.tsx
  src/app/[lang]/(home)/home/_components/news-box.tsx
  src/app/[lang]/(home)/home/_components/popular-interest-news.tsx
  src/app/[lang]/(home)/home/_components/recent-lookup.tsx
  src/app/[lang]/(home)/home/layout.tsx
  src/app/[lang]/(home)/layout.tsx
  src/app/[lang]/(mypage)/mypage/page.tsx
  src/app/[lang]/(report)/report/[stockReutersCode]/layout.tsx
  src/app/[lang]/(report)/report/_components/AccumulationBarChart.tsx
  src/app/[lang]/(report)/report/_components/ReportHeader.tsx
  src/app/[lang]/(report)/report/_components/StockChart.tsx
  src/components/common/List/NewsItem.tsx
  src/components/common/ReportCardHeader.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🐞 버그, ♻️ 리팩토링, 🛠️ 기능개발

#145 [QJ5-169] 마이페이지 메타 태그 추가
  src/app/[lang]/(auth)/withdraw/page.tsx
  src/app/[lang]/(mypage)/mypage/layout.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🛠️ 기능개발

#144 [QJ5-153] 발견, 관심 주식 페이지 메타 태그 적용 및 toast 구현
  src/app/[lang]/(discovery)/discovery/[search]/_components/DiscoveryStocks.tsx
  src/app/[lang]/(discovery)/discovery/[search]/layout.tsx
  src/app/[lang]/(discovery)/discovery/[search]/loading.tsx
  src/app/[lang]/(discovery)/discovery/layout.tsx
  src/app/[lang]/(mypage)/mypage/_api/getStockLangName.ts
  src/app/[lang]/(mypage)/mypage/_components/EditProfileForm.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockModalSection.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockRecentSearches.tsx
  src/app/[lang]/(mystock)/mystock/_components/SearchItem.tsx
  src/app/[lang]/(mystock)/mystock/layout.tsx
  src/app/[lang]/body-loading.tsx
  src/components/common/List/StockItem.tsx
  src/components/common/StockPrice.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: ♻️ 리팩토링, 🛠️ 기능개발

#146 fix: 메인 페이지 관심 주식 뉴스 항목 주식 아이콘 안 나오는 버그 수정
  src/actions/news.ts
  src/app/[lang]/(home)/home/_components/popular-interest-news.tsx
  src/components/common/Card.tsx
Labels: 🐞 버그

#142 [QJ5-170] 루트레이아웃, 뉴스페이지 메타데이터 작성
  src/app/[lang]/(news)/news/layout.tsx
  src/app/[lang]/layout.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🛠️ 기능개발

#148 feat: 네이버, 구글 TXT 레코드 메타 태그 추가
  src/app/[lang]/layout.tsx
Labels: ⚙️ 개발환경

#153 [QJ5-177] 로그인/회원가입 메타데이터 타이틀 적용되지 않는 이슈
  src/utils/metadata.ts
Labels: 🐞 버그

#155 [HOTFIX] SSE Event Source 최적화
  src/hooks/use-stock-price.ts
Labels: 🐞 버그

#157 [QJ5-178] 프로필 설정 프로필 설정 배포 이슈
  src/app/[lang]/(auth)/account/profile-setup/page.tsx
  src/utils/metadata.ts
Labels: 🐞 버그

#163 [QJ5-179] 여러가지 버그 수정 및 리팩토링 진행
  src/actions/search.ts
  src/app/[lang]/(mypage)/mypage/_components/MyPageMain.tsx
  src/app/[lang]/(mystock)/mystock/_components/MyStockFooter.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx
  src/app/globals.css
  src/components/common/Button.tsx
  src/hooks/use-alert.ts
Labels: 🐞 버그, ♻️ 리팩토링, 🎨 디자인
