Repository doksuri5/frontend, pull requests merged in 2024-08, with the labels that each got.

#165 [QJ5-178] 홈 layout shift 이슈 수정 및 stock chart tooltip 디자인 수정
  src/app/[lang]/(home)/home/_components/ai-reports.tsx
  src/app/[lang]/(home)/home/page.tsx
  src/app/[lang]/(report)/report/_components/StockChart.tsx
  src/app/[lang]/(report)/report/_components/StockTooltip.tsx
Labels: 🐞 버그

#166 [QJ5-181] 이슈 수정 파비콘 추가
  src/app/favicon.ico
Labels: 🐞 버그

#164 [QJ5-180] 메인페이지 텍스트 다국어 작업
  src/app/[lang]/(home)/page.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🛠️ 기능개발

#168 [QJ5-179] UI/UX 및 버그 수정
  src/app/[lang]/(auth)/_components/SocialLogin.tsx
  src/app/[lang]/(home)/home/_components/interest-stocks.tsx
  src/app/[lang]/(home)/home/_components/popular-interest-news.tsx
  src/app/[lang]/(home)/home/_components/recent-lookup.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/AiSummary.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/NewsDetail.tsx
  src/app/[lang]/(news)/news/[newsId]/_components/RelatedStocks.tsx
  src/app/[lang]/(news)/news/_components/NewsInfinityList.tsx
  src/components/common/Card.tsx
  src/components/common/ChatBot.tsx
  src/components/common/CircleSpinner.tsx
  src/components/common/List/FindNews.tsx
  src/components/common/List/NewsItem.tsx
  src/components/common/List/StockItem.tsx
  src/components/common/PoPularNews.tsx
  src/components/common/StockPrice.tsx
  src/components/layout/Header.tsx
Labels: 🐞 버그, ♻️ 리팩토링, 🎨 디자인

#170 [QJ5-173] 다국어 stocks 변경으로 인한 side effect
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
Labels: 🐞 버그

#171 [QJ5-181] 메인페이지 최적화
  src/app/[lang]/(home)/home/_components/ai-reports.tsx
  src/app/[lang]/(home)/home/_components/news-box.tsx
  src/app/[lang]/(home)/home/_components/report-title.tsx
  src/app/[lang]/(home)/home/layout.tsx
  src/app/[lang]/(home)/home/page.tsx
  src/app/[lang]/favicon.ico
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🐞 버그, ♻️ 리팩토링

#169 [QJ5-182] 사이트맵, 로봇txt 파일 추가 및 설정
  src/app/robots.txt
  src/app/sitemap.xml
  src/middleware.ts
Labels: ⚙️ 개발환경

#175 [QJ5-186] not-found 페이지 다국어 작업
  src/app/[lang]/not-found.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🛠️ 기능개발

#176 [QJ5-174] 뉴스 상세 페이지 메타태그 작성, 루트 description 글자수 60자 이내로 수정
  src/app/[lang]/(news)/news/[newsId]/layout.tsx
  src/dictionaries/ch.json
  src/dictionaries/en.json
  src/dictionaries/fr.json
  src/dictionaries/jp.json
  src/dictionaries/ko.json
Labels: 🛠️ 기능개발

#179 [QJ5-188] 닉네임 중복 확인 로딩 구현
  src/app/[lang]/(auth)/_components/ProfileSetUpForm.tsx
Labels: 🛠️ 기능개발

#180 [QJ5-187] 계정정보 수정 하단 회원탈퇴 버튼 스타일 수정
  src/app/[lang]/(mypage)/mypage/_components/PrivacyEditModal.tsx
Labels: 🎨 디자인
